add: eslint for TS react.js library
nadunindunil/material-jsonschema-form pull request #5
Opened 2019-10-21 10:03 UTC by sabesansathananthan

Setup eslint for TS react.js library #3

nadunindunil/material-jsonschema-form#3

2019-10-21 15:59 UTC, nadunindunil commented on package.json
> +  },
please add these libs into dev dependencies

2019-10-21 16:02 UTC, nadunindunil requested changes
please attend to requested

2019-10-21 18:55 UTC, sabesansathananthan commented
done !

2019-10-25 19:11 UTC, nadunindunil approved these changes
thank you

2019-10-25 19:12 UTC, merged